---

- name: Install nodejs
  sudo: True
  apt: pkg=nodejs state=installed

- name: Install npm
  sudo: True
  apt: pkg=npm state=installed

- name: Symlink nodejs to node
  sudo: True
  command: ln -s /usr/bin/nodejs /usr/bin/node
