---
- name: Add Dropbox KeyServer
  sudo: True
  command: apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E

- name: Add Dropbox PPA Repo
  sudo: True
  command: sudo add-apt-repository "deb http://linux.dropbox.com/ubuntu {{os_name}} main"

- name: Install Dropbox
  sudo: True
  apt: pkg=nautilus-dropbox state=installed
