---
- name: Does the Google apt file exist?
  sudo: True
  command: test -f /etc/apt/sources.list.d/google-chrome.list
  register: google_apt_exists
  ignore_errors: True

- name: Add Google Chrome key
  sudo: True
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
  sudo: True
  copy: src=google-chrome-apt-repo dest=/etc/apt/sources.list.d/google-chrome.list owner=root group=root mode=644
  when: google_apt_exists.rc == 1

- name: Update apt cache
  sudo: True
  apt: update_cache=yes
  when: google_apt_exists.rc == 1

- name: Install Google Chrome
  sudo: True
  apt: pkg=google-chrome-stable state=installed
