---
- name: Install Vim
  sudo: True
  apt: pkg=vim state=installed

- name: Install VCS's
  sudo: True
  apt: pkg={{item}} state=installed
  with_items:
    - git-core
    - mercurial

- name: Install cURL
  sudo: True
  apt: pkg=curl state=installed

- name: Install utilities
  sudo: True
  apt: pkg={{item}} state=installed
  with_items:
    - tree
    - feh
    - xclip

- { include: zsh.yml, tags: ['zsh', 'cli'] }
- { include: dropbox.yml, tags: ['gui', 'dropbox'] }
- { include: google-chrome.yml, tags: ['gui', 'google'] }
- { include: hubflow.yml, tags: ['hubflow','git'] }
