---
- name: Install PHP
  sudo: True
  apt: pkg={{item}} state=installed
  with_items:
    - php5-cli
    - php5-dev
    - php5-mysql
    - php5-json
    - php5-curl
    - php5-xdebug
    - libpcre3-dev
    - libcurl3-dev
    - libyaml-dev
